#!/bin/bash
#:  * `cacheclean`
#:
#:  Remove all cached downloads, and broken symlink files in cache directory.

# HOMEBREW_LIBRARY is set by bin/brew
# HOMEBREW_CACHE is set in brew.sh

# These variables are set from the user environment.
set -e

# shellcheck disable=SC1091
source "${HOMEBREW_LIBRARY}/Homebrew/utils/helpers.sh"

safe_cd "${HOMEBREW_CACHE}"

DOWNLOADS_SIZE="$(du -hs downloads | awk '{print$1}')"
declare -r DOWNLOADS_SIZE

echo "Downloads size: ${DOWNLOADS_SIZE}"

if [[ "${DOWNLOADS_SIZE}" = 0B ]]
then
  ohai "No downloads."
else
  ohai "Removing downloads..."
  rm downloads/*
fi

ohai "Removing broken symlink files..."
find -L . Cask -maxdepth 1 -type l -exec rm -f '{}' +
