#!/bin/bash
#:  * `update-schedule` [<schedule>|stop]
#:
#:  Register `brew update-log` scheduler.
#:
#:  *Note:* `<schedule>` must be describe as cron format.

# HOMEBREW_LIBRARY HOMEBREW_PREFIX are set by bin/brew
set -e

declare -r TAP_REPOSITORY=ichizok/homebrew-utils
declare -r TAP_DIRECTORY=${HOMEBREW_LIBRARY}/Taps/${TAP_REPOSITORY}

declare -r FORMULA_NAME=brew-update-scheduler
declare -r FORMULA_FILE=${TAP_DIRECTORY}/Formula/${FORMULA_NAME}.rb
declare -r FORMULA=${TAP_REPOSITORY/homebrew-/}/${FORMULA_NAME}

if [[ "$1" = stop ]]
then
  "${HOMEBREW_BREW_FILE}" services stop "${FORMULA}"
  exit 0
fi

declare -r UPDATE_SCHEDULE=${1:-"0 0 * * *"}

# shellcheck disable=SC1091
source "${HOMEBREW_LIBRARY}/Homebrew/utils/helpers.sh"

validate_format() {
  local fields
  read -r -a fields <<<"${UPDATE_SCHEDULE}"
  [[ "${#fields[@]}" -eq 5 ]] || return 1

  local i value values
  for i in {0..4}
  do
    read -r -a values <<<"${fields[$i]/,/ }"
    for value in "${values[@]}"
    do
      if [[ "${value}" =~ ^(\*|[[:digit:]]+|[[:digit:]]+-[[:digit:]]+)$ ]]
      then
        continue
      fi
      if [[ $i -eq 4 ]] && [[ "${value}" =~ ^(sun|mon|tue|wed|thu|fri|sat)$ ]]
      then
        continue
      fi
      return 1
    done
  done
}

validate_format || odie "\"${UPDATE_SCHEDULE}\" does not follow cron format."

cat <<EOT >"${FORMULA_FILE}"
class BrewUpdateScheduler < Formula
  desc "Brew-update scheduler"
  url "https://github.com/${TAP_REPOSITORY}/raw/main/README.md"
  sha256 "c8c40edbc278a694f5ad81c28cf54c6611210f9788dce25ff5a52e308f12e0be"
  version "1.0.0"

  keg_only "provides only service"

  depends_on "terminal-notifier"

  def install
    system "touch", prefix/"placeholder"
  end

  def caveats
    <<~EOS
      This formula provides only service for periodic \`brew update\`.

      You can manage the schedule through \`brew update-schedule\`:
        brew update-schedule [<schedule>|stop]
    EOS
  end

  service do
    run [HOMEBREW_BREW_FILE, "update-log"]
    run_at_load false
    run_type :cron
    cron "${UPDATE_SCHEDULE}"
    log_path HOMEBREW_LOGS/"update.log"
    error_log_path HOMEBREW_LOGS/"update.log"
  end

  test do; end
end
EOT

"${HOMEBREW_BREW_FILE}" reinstall "${FORMULA}"
"${HOMEBREW_BREW_FILE}" services restart "${FORMULA}"
